package com.icinfo.platform.elasticsearch.model;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_NUMBER
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_CATEGORY
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_AUTHOR
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_PUBLISHER
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_PUBLICATION_DATE
     *
     * @mbg.generated
     */
    private Date publicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_CREATOR
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_OPERATE_DATE
     *
     * @mbg.generated
     */
    private Date operateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ES_BOOK.EB_OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.ID
     *
     * @return the value of ES_BOOK.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.ID
     *
     * @param id the value for ES_BOOK.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_NUMBER
     *
     * @return the value of ES_BOOK.EB_NUMBER
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_NUMBER
     *
     * @param number the value for ES_BOOK.EB_NUMBER
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_TITLE
     *
     * @return the value of ES_BOOK.EB_TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_TITLE
     *
     * @param title the value for ES_BOOK.EB_TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_CATEGORY
     *
     * @return the value of ES_BOOK.EB_CATEGORY
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_CATEGORY
     *
     * @param category the value for ES_BOOK.EB_CATEGORY
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_AUTHOR
     *
     * @return the value of ES_BOOK.EB_AUTHOR
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_AUTHOR
     *
     * @param author the value for ES_BOOK.EB_AUTHOR
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_PUBLISHER
     *
     * @return the value of ES_BOOK.EB_PUBLISHER
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_PUBLISHER
     *
     * @param publisher the value for ES_BOOK.EB_PUBLISHER
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_PUBLICATION_DATE
     *
     * @return the value of ES_BOOK.EB_PUBLICATION_DATE
     *
     * @mbg.generated
     */
    public Date getPublicationDate() {
        return publicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_PUBLICATION_DATE
     *
     * @param publicationDate the value for ES_BOOK.EB_PUBLICATION_DATE
     *
     * @mbg.generated
     */
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_CREATE_DATE
     *
     * @return the value of ES_BOOK.EB_CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_CREATE_DATE
     *
     * @param createDate the value for ES_BOOK.EB_CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_CREATOR
     *
     * @return the value of ES_BOOK.EB_CREATOR
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_CREATOR
     *
     * @param creator the value for ES_BOOK.EB_CREATOR
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_OPERATE_DATE
     *
     * @return the value of ES_BOOK.EB_OPERATE_DATE
     *
     * @mbg.generated
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_OPERATE_DATE
     *
     * @param operateDate the value for ES_BOOK.EB_OPERATE_DATE
     *
     * @mbg.generated
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ES_BOOK.EB_OPERATOR
     *
     * @return the value of ES_BOOK.EB_OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ES_BOOK.EB_OPERATOR
     *
     * @param operator the value for ES_BOOK.EB_OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}